# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/clj-pulse. DO NOT EDIT.
class CljPulse < Formula
  desc "Language server for Clojure"
  homepage "https://github.com/abogoyavlensky/clj-pulse"
  version "0.1.3"
  license "MIT"

  livecheck do
    skip "Formula is updated by clj-pulse release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.1.3/clj-pulse-x86_64-apple-darwin.tar.gz"
      sha256 "d03fac8e8677bcfc3538ef757a348bd83717f0259cf9fc80cb9f0c7fdb2a9841"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.1.3/clj-pulse-aarch64-apple-darwin.tar.gz"
      sha256 "e7d93029705ee70d8a0f3e1203f35d50dbceef3b8e9f2a8e9b89aa906deb0ae9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.1.3/clj-pulse-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f27cb56e1819a159fbbec708d7a0bade225a50067bb3b95ea96b859ec6aae50c"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.1.3/clj-pulse-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b7958d42f2e7ef8d10f302e46ef5630e5495e40dc9913b27a6b2ab087c224233"
    end
  end

  def install
    bin.install "clj-pulse"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clj-pulse --version")
  end
end
