# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/clj-pulse. DO NOT EDIT.
class CljPulse < Formula
  desc "Language server for Clojure"
  homepage "https://github.com/abogoyavlensky/clj-pulse"
  version "0.5.4"
  license "MIT"

  livecheck do
    skip "Formula is updated by clj-pulse release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.5.4/clj-pulse-x86_64-apple-darwin.tar.gz"
      sha256 "6c71842c34c1d4edd333780432787022578d7aea19e3f0bf8f67a03346cdb915"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.5.4/clj-pulse-aarch64-apple-darwin.tar.gz"
      sha256 "fb8536ea45719680dd2c32590818475fa2aabcd64f125c4fc9241a0c35c2f28c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.5.4/clj-pulse-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5784e02f39d6b8c1b5cabe244ffb5834673f960b4f2838550689733ae24e325e"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.5.4/clj-pulse-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "91f2e87ead7f503dba45ff42d525294a365dde343a6523e1ab66f7fa3235db49"
    end
  end

  def install
    bin.install "clj-pulse"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clj-pulse --version")
  end
end
