# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/clj-pulse. DO NOT EDIT.
class CljPulse < Formula
  desc "Language server for Clojure"
  homepage "https://github.com/abogoyavlensky/clj-pulse"
  version "0.5.3"
  license "MIT"

  livecheck do
    skip "Formula is updated by clj-pulse release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.5.3/clj-pulse-x86_64-apple-darwin.tar.gz"
      sha256 "bad162c48905d205ea9daef20c54c0361b4ec4ab3a34382a9033be6c7a4b0ae6"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.5.3/clj-pulse-aarch64-apple-darwin.tar.gz"
      sha256 "86d324302b95cc43cb23a4e9c2dac8fd5943a4c8de8b3d8b3167664a1ab61d14"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.5.3/clj-pulse-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "271fd5b640f6c11e12200aa15bdbc98d86f3e0d4173f558b73c3b3e28f4a0cc4"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/clj-pulse/releases/download/v0.5.3/clj-pulse-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "894acb5ddb1a215c517a1228aadc740bf870a751e98f0f4278753ca1e6cbe8d9"
    end
  end

  def install
    bin.install "clj-pulse"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clj-pulse --version")
  end
end
