# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/frame. DO NOT EDIT.
class Frame < Formula
  desc "Declarative project templater"
  homepage "https://github.com/abogoyavlensky/frame"
  version "0.1.1"
  license "MIT"

  livecheck do
    skip "Formula is updated by frame release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.1/frame_0.1.1_darwin_amd64.tar.gz"
      sha256 "f3712fdeff86db6a74fd1b3bed84623d30471bd8d3677424f9d9c6786ac41dfe"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.1/frame_0.1.1_darwin_arm64.tar.gz"
      sha256 "26aa3a57453acac3d205d97c61d3f80dc2c4de0fbb9f454c398ce980e28f2989"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.1/frame_0.1.1_linux_amd64.tar.gz"
      sha256 "c3fb228a8e2635ede353e3a4843d0c7a87ab6504580641aec08d52b552e783e6"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.1/frame_0.1.1_linux_arm64.tar.gz"
      sha256 "8c7948aec3c72ecc2ba6b274782b2f3c98906bffdffdda4a10d6540196403267"
    end
  end

  def install
    bin.install "frame"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/frame --version")
  end
end
