# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/frame. DO NOT EDIT.
class Frame < Formula
  desc "Declarative project templater"
  homepage "https://github.com/abogoyavlensky/frame"
  version "0.1.3"
  license "MIT"

  livecheck do
    skip "Formula is updated by frame release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.3/frame_0.1.3_darwin_amd64.tar.gz"
      sha256 "11cb2e22e3715a6f40de9aa5740b5da629ce633736e642a916712ba354b6d22e"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.3/frame_0.1.3_darwin_arm64.tar.gz"
      sha256 "3018bb569b698ad617c505475bd1d87aaf52c7381d94c51d2b112b9fc3fe8cf8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.3/frame_0.1.3_linux_amd64.tar.gz"
      sha256 "8a0107ed036db81dcce544e44d0ba9119c149ed4c3289fdf2c12f1ad625df549"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.3/frame_0.1.3_linux_arm64.tar.gz"
      sha256 "e567d9fe779d99dab43f7e51a639677d82365368d7550060796ed43ed5ea8bd3"
    end
  end

  def install
    bin.install "frame"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/frame --version")
  end
end
