# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/frame. DO NOT EDIT.
class Frame < Formula
  desc "Declarative project templater"
  homepage "https://github.com/abogoyavlensky/frame"
  version "0.1.0"
  license "MIT"

  livecheck do
    skip "Formula is updated by frame release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.0/frame_0.1.0_darwin_amd64.tar.gz"
      sha256 "686b0dc092dcc52528575402f70d9fa1e0ad7f038498966db1b6c64df3ea3bf8"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.0/frame_0.1.0_darwin_arm64.tar.gz"
      sha256 "f6ec5c6c1a831993a707c4c03287e0811fdb2b282965f14b18af3b93782c8f5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.0/frame_0.1.0_linux_amd64.tar.gz"
      sha256 "ec3350d80e6b1b16ee73c8367154e3c094fb42bd39e7b21dbc9a2f2b700a2461"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/frame/releases/download/v0.1.0/frame_0.1.0_linux_arm64.tar.gz"
      sha256 "15ab7977b10c1287a6290ab297f345629e074d266961926a56249feac638fa41"
    end
  end

  def install
    bin.install "frame"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/frame --version")
  end
end
