# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/lgx. DO NOT EDIT.
class Lgx < Formula
  desc "Package and project manager for the let-go Clojure dialect"
  homepage "https://github.com/abogoyavlensky/lgx"
  version "0.4.0"
  license "MIT"

  livecheck do
    skip "Formula is updated by lgx release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.4.0/lgx_0.4.0_darwin_amd64.tar.gz"
      sha256 "b7ca3d909bfd5b15aafb00730605c64212750661ed5ddaa412e3efd02b1c9df4"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.4.0/lgx_0.4.0_darwin_arm64.tar.gz"
      sha256 "df13407870b9501034f08ba8addd6ff03777790493ec56b4bf78abddd18e6405"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.4.0/lgx_0.4.0_linux_amd64.tar.gz"
      sha256 "491f01693cd5dabfc154a442cdf81d88b35e744bae60d170ac006d5b141e9f1b"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.4.0/lgx_0.4.0_linux_arm64.tar.gz"
      sha256 "b3cf36164bb9cef77c0987aa11d5bea1a3c443f480a38728728327bd01ed1632"
    end
  end

  def install
    bin.install "lgx"
  end

  def caveats
    <<~EOS
      lgx needs the let-go compiler (lg >= 1.11.0) on PATH:
        brew install nooga/tap/let-go
      Other options: https://github.com/abogoyavlensky/lgx#requirements
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lgx --version")
  end
end
