# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/lgx. DO NOT EDIT.
class Lgx < Formula
  desc "Package and project manager for the let-go Clojure dialect"
  homepage "https://github.com/abogoyavlensky/lgx"
  version "0.1.0-rc3"
  license "MIT"

  livecheck do
    skip "Formula is updated by lgx release CI"
  end

  depends_on "nooga/tap/let-go"

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.1.0-rc3/lgx_0.1.0-rc3_darwin_amd64.tar.gz"
      sha256 "42626926fb8070c26b5f20fd60dfb9e586073bdd5b3674a2e49a04485e8db958"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.1.0-rc3/lgx_0.1.0-rc3_darwin_arm64.tar.gz"
      sha256 "e9756cca992ae259054a9bbb693556c08e29b301254524b61da950760ed79346"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.1.0-rc3/lgx_0.1.0-rc3_linux_amd64.tar.gz"
      sha256 "c9ce564f6f57cd144733cff96fe8dc1e6ad8f832f009214123a1db09bb747d40"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.1.0-rc3/lgx_0.1.0-rc3_linux_arm64.tar.gz"
      sha256 "7187ccac39fe3228f1476b6ebccbdb099cbf3a490f43af83f7f1656903317d58"
    end
  end

  def install
    bin.install "lgx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lgx --version")
  end
end
