# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/lgx. DO NOT EDIT.
class Lgx < Formula
  desc "Package and project manager for the let-go Clojure dialect"
  homepage "https://github.com/abogoyavlensky/lgx"
  license "MIT"

  livecheck do
    skip "Formula is updated by lgx release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.1.0-rc2/lgx_0.1.0-rc2_darwin_amd64.tar.gz"
      sha256 "525a6c9f6831969abcf54970a975fbd10a8749091d3697676b3f32e86486ac16"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.1.0-rc2/lgx_0.1.0-rc2_darwin_arm64.tar.gz"
      sha256 "38cbcfb8d99ab552e58d928b94d50e56730279ef08746646185704329f1504cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.1.0-rc2/lgx_0.1.0-rc2_linux_amd64.tar.gz"
      sha256 "e17d33f7bd6bec5259a245f365cd883371f91eed7373eb4724fabf867f14d602"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/lgx/releases/download/v0.1.0-rc2/lgx_0.1.0-rc2_linux_arm64.tar.gz"
      sha256 "e7a91494d61f90c5bb3aca14b9e6ca107138fbf1d74d7725e688bca4035a89a5"
    end
  end

  def install
    bin.install "lgx"
  end

  def caveats
    <<~EOS
      lgx requires the let-go compiler (lg >= 1.10.0) on PATH.
      On macOS:
        brew tap nooga/let-go https://github.com/nooga/let-go && brew install let-go
      On Linux (and other options): https://github.com/abogoyavlensky/lgx#requirements
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lgx --version")
  end
end
