# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/nreplctl. DO NOT EDIT.
class Nreplctl < Formula
  desc "Evaluate Clojure code in a running nREPL server and print the results"
  homepage "https://github.com/abogoyavlensky/nreplctl"
  version "0.1.0"
  license "MIT"

  livecheck do
    skip "Formula is updated by nreplctl release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/nreplctl/releases/download/v0.1.0/nreplctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "20aefee5e12f62a47b53966407bef6a69fd549e03fbd0484130af70aae2e3140"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/nreplctl/releases/download/v0.1.0/nreplctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "11785966e48f982cdba47a9f090f9011e2f4a46552b32a7041a69b9b57cca082"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/nreplctl/releases/download/v0.1.0/nreplctl_0.1.0_linux_amd64.tar.gz"
      sha256 "7803045cd4a08e1e301a72c7bbbeaecfd2fa7ad4ccb7a46e9e144b68997fc8fb"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/nreplctl/releases/download/v0.1.0/nreplctl_0.1.0_linux_arm64.tar.gz"
      sha256 "cd2ff720ace4c2c060447b6e501d6c16ac2b23221e97904edced1e85ffd1edce"
    end
  end

  def install
    bin.install "nreplctl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nreplctl --version")
  end
end
