# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/rite. DO NOT EDIT.
class Rite < Formula
  desc "Task runner for any project with an embedded let-go runtime"
  homepage "https://github.com/abogoyavlensky/rite"
  version "0.1.0"
  license "MIT"

  livecheck do
    skip "Formula is updated by rite release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.1.0/rite_0.1.0_darwin_amd64.tar.gz"
      sha256 "8ae929c3583932697dcbdc32ba67930c8dbec12bb0bf65bf629154e9007d9f63"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.1.0/rite_0.1.0_darwin_arm64.tar.gz"
      sha256 "202d05286cdf0bcea135cbf497925ec77c05485d824896aad74c6b93da5e26ad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.1.0/rite_0.1.0_linux_amd64.tar.gz"
      sha256 "b1bd9ff1d3164a307612e28a2d7426add75930fd8bf5fe96dd2c45d00213f2ec"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.1.0/rite_0.1.0_linux_arm64.tar.gz"
      sha256 "c1d809ee1adbffdd9f69c542515302e4a66d128d75e57cb7e6d82a9d705d164c"
    end
  end

  def install
    bin.install "rite"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rite --version")
  end
end
