# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/rite. DO NOT EDIT.
class Rite < Formula
  desc "Task runner with an embedded let-go runtime"
  homepage "https://github.com/abogoyavlensky/rite"
  version "0.2.0"
  license "MIT"

  livecheck do
    skip "Formula is updated by rite release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.2.0/rite_0.2.0_darwin_amd64.tar.gz"
      sha256 "905b9c6eb98dc249551c2e07a0d86958a3e8483f62063e2169e970a06a5343ac"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.2.0/rite_0.2.0_darwin_arm64.tar.gz"
      sha256 "fbba191f2a642078493bcd6d1f2b97851b5e48e242ec47e99c121d17edfec71e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.2.0/rite_0.2.0_linux_amd64.tar.gz"
      sha256 "f5d41efe5a7d714b506e472182a21edec408b955f14da5421ac0c562e1dab100"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.2.0/rite_0.2.0_linux_arm64.tar.gz"
      sha256 "5bdd59923f671006650724421c2b5cb52ae4a288356e0b8b9ce5b3cc6b4c63f9"
    end
  end

  def install
    bin.install "rite"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rite --version")
  end
end
