# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/rite. DO NOT EDIT.
class Rite < Formula
  desc "Task runner for any project with an embedded let-go runtime"
  homepage "https://github.com/abogoyavlensky/rite"
  version "0.1.1"
  license "MIT"

  livecheck do
    skip "Formula is updated by rite release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.1.1/rite_0.1.1_darwin_amd64.tar.gz"
      sha256 "7a90117e50cefa44476636a3d6817ee0e27a8c1ea6e28c4ec1e4993094786cbf"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.1.1/rite_0.1.1_darwin_arm64.tar.gz"
      sha256 "5d50b104a68695a4f3a7acbd22dbb3c15f348ee14eca6c6f5f404ba95faf26b8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.1.1/rite_0.1.1_linux_amd64.tar.gz"
      sha256 "199871463eca7932b1aa4e8dc36501ec25c890cc44efacf7e5f0654001ef664f"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/rite/releases/download/v0.1.1/rite_0.1.1_linux_arm64.tar.gz"
      sha256 "49046f675050220c95c4827a4c421fc01b994cac2f67009794c1371097b29409"
    end
  end

  def install
    bin.install "rite"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rite --version")
  end
end
