# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/skl. DO NOT EDIT.
class Skl < Formula
  desc "Fetch and install agent skills from any git repository"
  homepage "https://github.com/abogoyavlensky/skl"
  version "0.1.1"
  license "MIT"

  livecheck do
    skip "Formula is updated by skl release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.1/skl_0.1.1_darwin_amd64.tar.gz"
      sha256 "ad5f1b3fe88468a73e7098e55dba2bd7395646827eacd351f82681506e1bb28b"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.1/skl_0.1.1_darwin_arm64.tar.gz"
      sha256 "48c96eb619c44cc95c9922ab3238ef47b8b4c39eadc3d0e68fc25f12f9408be5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.1/skl_0.1.1_linux_amd64.tar.gz"
      sha256 "509b3e439859e0e9bcbcc2280f1a6f2320174ee40ca5ef2ac4f5ec0f53706211"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.1/skl_0.1.1_linux_arm64.tar.gz"
      sha256 "438d14c68a292658af8c83c064bd0f5008f10448731cf724c04f9eef215a5ff3"
    end
  end

  def install
    bin.install "skl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skl --version")
  end
end
