# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/skl. DO NOT EDIT.
class Skl < Formula
  desc "Fetch and install agent skills from any git repository"
  homepage "https://github.com/abogoyavlensky/skl"
  version "0.1.0"
  license "MIT"

  livecheck do
    skip "Formula is updated by skl release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.0/skl_0.1.0_darwin_amd64.tar.gz"
      sha256 "1f35e77abccd2f5018ed2d9b216d458a2ea8956b9433c7ce273b927c4aa79c5d"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.0/skl_0.1.0_darwin_arm64.tar.gz"
      sha256 "1e9b9f0cbe686567779933cc7dba2b5b35b2c49f18c9a0fe2eab1a043ff2ca84"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.0/skl_0.1.0_linux_amd64.tar.gz"
      sha256 "283f37bd2b2fb5fcd1d964feeb768d482f23e9b49b5a56f4008bcb97791337ca"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.0/skl_0.1.0_linux_arm64.tar.gz"
      sha256 "0f1562c53a9776e8815810bfdcbbd55b57000c3b3ce0f20353e106aeac0b0206"
    end
  end

  def install
    bin.install "skl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skl --version")
  end
end
