# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/skl. DO NOT EDIT.
class Skl < Formula
  desc "Fetch and install agent skills from any git repository"
  homepage "https://github.com/abogoyavlensky/skl"
  version "0.1.4"
  license "MIT"

  livecheck do
    skip "Formula is updated by skl release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.4/skl_0.1.4_darwin_amd64.tar.gz"
      sha256 "0791d558e33b31bad9142e44809344881c566f149d4c0f177d8016bd15ef3322"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.4/skl_0.1.4_darwin_arm64.tar.gz"
      sha256 "2d2a53948cecfeaa9af9a9fcb1c68899c6a288f8508bb89b68d5adecc49cc268"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.4/skl_0.1.4_linux_amd64.tar.gz"
      sha256 "a3c37b95f33218a7734c7dcaaf85634bc9a27313a2d5bcf9573fd2a561d2a37b"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/skl/releases/download/v0.1.4/skl_0.1.4_linux_arm64.tar.gz"
      sha256 "b77fdb1a3af525ea0435790148d2833fed460a54c482977fee19ecb4b702b81d"
    end
  end

  def install
    bin.install "skl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skl --version")
  end
end
