# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/wtr. DO NOT EDIT.
class Wtr < Formula
  desc "Git worktree router for managing multiple worktrees"
  homepage "https://github.com/abogoyavlensky/wtr"
  version "0.1.3"
  license "MIT"

  livecheck do
    skip "Formula is updated by wtr release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.1.3/wtr_0.1.3_darwin_amd64.tar.gz"
      sha256 "495ce027e9b2938e09ee47d0e0eb0c701e16be2836a730c92b8030fc10d28a88"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.1.3/wtr_0.1.3_darwin_arm64.tar.gz"
      sha256 "e2f97ab2f8d57ff255bdd897de0f60e930f6bfec40e46c68691ac7a7c7f0a16d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.1.3/wtr_0.1.3_linux_amd64.tar.gz"
      sha256 "6bca2fc51f234eb6ee9a396017aad37f3ae49c02db6424e5410ab256d3e49da2"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.1.3/wtr_0.1.3_linux_arm64.tar.gz"
      sha256 "36f8878cc9521d44025eef9905384b02136c4753e3a661841cfc5ee14c94c4c3"
    end
  end

  def install
    bin.install "wtr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wtr --version")
  end
end
