# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/wtr. DO NOT EDIT.
class Wtr < Formula
  desc "Git worktree router for managing multiple worktrees"
  homepage "https://github.com/abogoyavlensky/wtr"
  version "0.1.4"
  license "MIT"

  livecheck do
    skip "Formula is updated by wtr release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.1.4/wtr_0.1.4_darwin_amd64.tar.gz"
      sha256 "2f2ff85df062a7c17405605571124e1aa3bd94c083bdf9811b7749ac0db3a992"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.1.4/wtr_0.1.4_darwin_arm64.tar.gz"
      sha256 "95cffe0886a8d97c9840806e75ea71e610780c59757ef6bceb529c3c176f90fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.1.4/wtr_0.1.4_linux_amd64.tar.gz"
      sha256 "a8001f5b1a90bc7b1c6149686f7f7a6930f87835021da03595ce150fcabbfded"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.1.4/wtr_0.1.4_linux_arm64.tar.gz"
      sha256 "5fb24f67ed10990ae10706389f46a6304d8eb4e39367083ed2901f32ecfed6a7"
    end
  end

  def install
    bin.install "wtr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wtr --version")
  end
end
