# This file is generated by scripts/generate-formula.sh in
# https://github.com/abogoyavlensky/wtr. DO NOT EDIT.
class Wtr < Formula
  desc "Git worktree router for managing multiple worktrees"
  homepage "https://github.com/abogoyavlensky/wtr"
  version "0.2.2"
  license "MIT"

  livecheck do
    skip "Formula is updated by wtr release CI"
  end

  on_macos do
    on_intel do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.2.2/wtr_0.2.2_darwin_amd64.tar.gz"
      sha256 "6fb24bf21c535f7bae43ac5ce5b2f59dbfe5d0a13d19e9fb8c0f99a43decffc4"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.2.2/wtr_0.2.2_darwin_arm64.tar.gz"
      sha256 "4a23a10a43c027e13179e0229dc15a8b2ce11bed9c47d0355ba85c7372262a25"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.2.2/wtr_0.2.2_linux_amd64.tar.gz"
      sha256 "a22e9174b7640753a414e74f7b5dd43a26e1144fe4a6b96a2f8d2859ef286b72"
    end
    on_arm do
      url "https://github.com/abogoyavlensky/wtr/releases/download/v0.2.2/wtr_0.2.2_linux_arm64.tar.gz"
      sha256 "d231b423952ed60e49dccf21e07ae8a2c6252ab1df64183da886c4a9392b582c"
    end
  end

  def install
    bin.install "wtr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wtr --version")
  end
end
